#Download base image ubuntu 16.04
FROM ubuntu:16.04

# Update Ubuntu Software repository
RUN apt-get update && \
    apt-get -y install \
    php7.0 \
    php7.0-cgi \
    php7.0-cli \
    php7.0-common \
    php7.0-curl \
	php7.0-dev \
	php7.0-json \
	php7.0-odbc \
	php7.0-mcrypt \
	unzip \
	apt-transport-https \
	autoconf && apt-get clean

# In order to remove further error. 
# E: The method driver /usr/lib/apt/methods/https could not be found.
# E: Failed to fetch https://apt-mo.trafficmanager.net/repos/mssql-ubuntu-xenial-release/dists/xenial/InRelease
#RUN apt-get install apt-transport-https	
	
#install ODBC driver
RUN echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/mssql-ubuntu-xenial-release/ xenial main" > /etc/apt/sources.list.d/mssqlpreview.list
RUN apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql unixodbc-dev-utf16


#Either Install git / download zip (One can see other strategies : https://ryanfb.github.io/etc/2015/07/29/git_strategies_for_docker.html )

#Get Source code

#RUN git clone https://github.com/Microsoft/msphpsql.git

RUN curl -sSL -o PHP-7.0-Linux.zip https://github.com/Microsoft/msphpsql/archive/PHP-7.0-Linux.zip

RUN unzip PHP-7.0-Linux.zip -d /REPO/
			
