#Download base image ubuntu 16.04
FROM ubuntu:16.04

# Update Ubuntu Software repository
RUN apt-get update && \
	apt-get -y install \
	php7.0.12 \
	php7.0.12-cgi \
	php7.0.12-cli \
	php7.0.12-common \
	php7.0.12-curl \
	php7.0.12-dev \
	php7.0.12-json \
	php7.0.12-odbc \
	php7.0.12-mcrypt \
	unzip \
	apt-transport-https \
	apache2	\
	libapache2-mod-php7.0.12	\
	autoconf && apt-get clean

	
# Enable apache mods.
RUN a2enmod php7.0.12
RUN a2enmod rewrite


#install ODBC driver
RUN echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/mssql-ubuntu-xenial-release/ xenial main" > /etc/apt/sources.list.d/mssqlpreview.list
RUN apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql unixodbc-dev-utf16

# Install msphpsql package...
RUN curl -sSL -o PHP-7.0-Linux.zip https://github.com/Microsoft/msphpsql/archive/PHP-7.0-Linux.zip

RUN unzip PHP-7.0-Linux.zip -d /REPO/


